from bs4 import BeautifulSoup
import requests as request
from collections import Counter

nations = [
    "Ả Rập Xê Út",
    "Afghanistan",
    "Ai Cập",
    "Albania",
    "Algeria",
    "Ấn Độ",
    "Andorra",
    "Angola",
    "Anh",
    "Antigua và Barbuda",
    "Áo",
    "Argentina",
    "Armenia",
    "Azerbaijan",
    "Ba Lan",
    "Bắc Macedonia",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belize",
    "Bénin",
    "Bhutan",
    "Bỉ",
    "Bờ Biển Ngà",
    "Bồ Đào Nha",
    "Bolivia",
    "Bosnia và Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Các tiểu vương quốc Ả Rập Thống nhất",
    "Cameroon",
    "Campuchia",
    "Canada",
    "Cape",
    "Verde",
    "Chad",
    "Chile",
    "Colombia",
    "Comoros",
    "Cộng hòa Congo",
    "Cộng hòa dân chủ Congo",
    "Cộng hòa Dominican",
    "Cộng hòa Séc",
    "Cộng hòa Trung Phi",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Djibouti",
    "Dominica",
    "Đài Loan",
    "Đan Mạch",
    "Đông Timor",
    "Đức",
    "Ecuador",
    "El Salvador",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Gabon",
    "Gambia",
    "Georgia",
    "Ghana",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea Xích đạo",
    "Guinea-Bissau",
    "Guyana",
    "Hà Lan",
    "Haiti",
    "Hàn Quốc",
    "Hoa Kỳ",
    "Mỹ",
    "Honduras",
    "Hungary",
    "Hy Lạp",
    "Iceland",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Jamaica",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Lào",
    "Latvia",
    "Lesotho",
    "Lebanon",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Liên bang Micronesia",
    "Lithuania",
    "Luxembourg",
    "Morocco",
    "Ma rốc",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Monaco",
    "Mông Cổ",
    "Montenegro",
    "Mozambique",
    "Myanmar",
    "Na Uy",
    "Nam Phi",
    "Nam Sudan",
    "Namibia",
    "Nauru",
    "Nepal",
    "New Zealand",
    "Nga",
    "Nhật Bản",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Phần Lan",
    "Pháp",
    "Philippines",
    "Qatar",
    "Quần đảo Marshall",
    "Quần đảo Solomon",
    "Romania",
    "Rwanda",
    "Saint Kitts và Nevis Saint Lucia",
    "Saint Vincent và Grenadines",
    "Samoa",
    "San Marino",
    "São Tomé và Príncipe",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Síp",
    "Slovakia",
    "Slovenia",
    "Somalia",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Tây Ban Nha",
    "Thái Lan",
    "Vatican",
    "Thổ Nhĩ Kỳ",
    "Thụy Điển",
    "Thụy Sĩ",
    "Togo",
    "Tonga",
    "Triều Tiên",
    "Trinidad và Tobago",
    "Trung Quốc",
    "Tunisia",
    "Turkmenistan",
    "Tuvalu",
    "Úc",
    "Uganda",
    "Ukraine",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Việt Nam",
    "Ý",
    "Italia",
    "Italy" "Yemen",
    "Zambia",
    "Zimbabwe",
]


class News:
    def __init__(self):
        self.document = request.get("https://vnexpress.net/rss/the-gioi.rss")
        self.obj = BeautifulSoup(self.document.text, "lxml").rss.channel
        self.articles = self.obj.find_all("item")
        self.titles = self._titlesRetrieve()  # return as list

    def _titlesRetrieve(self) -> list:
        rel = []
        for element in self.articles:
            rel.append(element.title.text)
        return rel

    def nationsAppearance(self) -> dict:
        rel = []
        listOfNations = []
        for title in self.titles:
            for nation in nations:
                # if found nation in titles
                if title.find(nation) != -1:
                    # if the nations's exists yet
                    listOfNations.append(nation)
        pair = Counter(listOfNations)
        for i in pair:
            rel.append({"nation": i, "number": pair[i]})
        return rel
